"""Phase A — Coverage probe.

Runs a series of wide-area showMapTrafos queries to empirically determine:
  1. Whether the API returns any transformers outside Cali proper.
  2. The true geographic bounds of the dataset (used to configure the main crawl).
  3. Whether the API has a per-response result cap.

Outputs data/coverage_probe.md with findings.
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass
from pathlib import Path

from emcali_session import bootstrap_session

# Scripts live in scripts/; data lives in the repo root data/ (one level up).
DATA_DIR = Path(__file__).resolve().parent.parent / "data"
RAW_DIR = DATA_DIR / "raw_probe"
OUT_MD = DATA_DIR / "coverage_probe.md"


@dataclass
class ProbeRegion:
    name: str
    min_lat: float
    min_lng: float
    max_lat: float
    max_lng: float
    note: str = ""


PROBE_REGIONS: list[ProbeRegion] = [
    ProbeRegion("Cali metro (documented)",    3.35, -76.58, 3.52, -76.47, "doc's nominal bounds"),
    ProbeRegion("Valle del Cauca (wide)",     3.00, -77.20, 4.90, -75.70, "whole department"),
    ProbeRegion("Yumbo (N neighbor)",         3.53, -76.54, 3.62, -76.46, "just north of Cali"),
    ProbeRegion("Jamundi (S neighbor)",       3.22, -76.58, 3.34, -76.48, "just south"),
    ProbeRegion("Palmira (E)",                3.48, -76.35, 3.65, -76.25, "east"),
    ProbeRegion("Candelaria (E)",             3.38, -76.40, 3.47, -76.30, "east"),
    ProbeRegion("Dagua / La Cumbre (W)",      3.55, -76.78, 3.75, -76.60, "west mountains"),
    ProbeRegion("Buenaventura (Pacific)",     3.80, -77.10, 3.95, -76.95, "pacific coast"),
    ProbeRegion("Cartago (far N Valle)",      4.70, -75.95, 4.80, -75.85, "far north, Valle"),
    ProbeRegion("Bogota control",             4.55, -74.15, 4.80, -73.95, "far control"),
    ProbeRegion("Medellin control",           6.18, -75.65, 6.32, -75.50, "far control"),
    ProbeRegion("Tiny empty bbox (ocean)",    3.80, -78.00, 3.85, -77.95, "sanity: 0 expected"),
]


def summarize(trafos: list[dict]) -> dict:
    if not trafos:
        return {"count": 0}
    lats = [t["latTrafo"] for t in trafos if t.get("latTrafo") is not None]
    lngs = [t["lngTrafo"] for t in trafos if t.get("lngTrafo") is not None]
    ciudades: dict[str, int] = {}
    barrios: dict[str, int] = {}
    propietarios: dict[str, int] = {}
    for t in trafos:
        c = str(t.get("codCiudad", ""))
        b = str(t.get("codBarrio", ""))
        p = str(t.get("codPropietario", ""))
        ciudades[c] = ciudades.get(c, 0) + 1
        barrios[b] = barrios.get(b, 0) + 1
        propietarios[p] = propietarios.get(p, 0) + 1
    return {
        "count": len(trafos),
        "lat_min": min(lats),
        "lat_max": max(lats),
        "lng_min": min(lngs),
        "lng_max": max(lngs),
        "codCiudad_hist": ciudades,
        "codPropietario_hist": propietarios,
        "codBarrio_unique": len(barrios),
        "first": {
            "codTrafo": trafos[0].get("codTrafo"),
            "dirTrafo": trafos[0].get("dirTrafo"),
            "latTrafo": trafos[0].get("latTrafo"),
            "lngTrafo": trafos[0].get("lngTrafo"),
        },
    }


def main() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    RAW_DIR.mkdir(parents=True, exist_ok=True)

    print("[probe] bootstrapping session...")
    es = bootstrap_session()

    all_results: list[tuple[ProbeRegion, dict]] = []

    for region in PROBE_REGIONS:
        print(f"\n[probe] {region.name}: "
              f"({region.min_lat}, {region.min_lng}) -> "
              f"({region.max_lat}, {region.max_lng})")
        try:
            raw = es.fetch_trafos(
                region.min_lat, region.min_lng, region.max_lat, region.max_lng,
                timeout=180.0,
            )
        except Exception as e:
            print(f"  ERROR: {e}")
            all_results.append((region, {"error": str(e)}))
            continue
        trafos = raw.get("trafos", [])
        summary = summarize(trafos)
        print(f"  -> {summary.get('count', 0)} transformers")
        if summary.get("count", 0):
            print(f"     bbox: lat [{summary['lat_min']:.4f}, {summary['lat_max']:.4f}], "
                  f"lng [{summary['lng_min']:.4f}, {summary['lng_max']:.4f}]")
            print(f"     codCiudad: {summary['codCiudad_hist']}")
            print(f"     codPropietario: {summary['codPropietario_hist']}")

        slug = region.name.lower().replace(" ", "_").replace("/", "_").replace("(", "").replace(")", "")
        (RAW_DIR / f"{slug}.json").write_text(json.dumps(raw, ensure_ascii=False, indent=2))

        all_results.append((region, summary))
        time.sleep(1.5)

    # Write markdown summary.
    lines = [
        "# EMCALI Coverage Probe — Findings",
        "",
        "This file is auto-generated by `probe_coverage.py`. It records empirical",
        "results from the showMapTrafos API for bounding boxes covering Cali and",
        "surrounding regions, plus far-away control cities.",
        "",
        "## Summary Table",
        "",
        "| Region | bbox (min_lat,min_lng,max_lat,max_lng) | count | observed lat range | observed lng range | codCiudad |",
        "|---|---|---:|---|---|---|",
    ]
    for region, summary in all_results:
        bbox = f"{region.min_lat},{region.min_lng},{region.max_lat},{region.max_lng}"
        if "error" in summary:
            lines.append(f"| {region.name} | {bbox} | ERROR | — | — | {summary['error']} |")
            continue
        count = summary.get("count", 0)
        if count == 0:
            lines.append(f"| {region.name} | {bbox} | 0 | — | — | — |")
        else:
            lat_range = f"[{summary['lat_min']:.4f}, {summary['lat_max']:.4f}]"
            lng_range = f"[{summary['lng_min']:.4f}, {summary['lng_max']:.4f}]"
            ciudad = ", ".join(f"{k}:{v}" for k, v in sorted(summary["codCiudad_hist"].items(), key=lambda x: -x[1]))
            lines.append(f"| {region.name} | {bbox} | {count} | {lat_range} | {lng_range} | {ciudad} |")

    # Interpretation.
    cali = next((s for r, s in all_results if r.name == "Cali metro (documented)"), {})
    valle = next((s for r, s in all_results if r.name.startswith("Valle del Cauca")), {})
    controls = [(r.name, s) for r, s in all_results
                if r.name in ("Bogota control", "Medellin control", "Tiny empty bbox (ocean)")]

    lines += [
        "",
        "## Interpretation",
        "",
        f"- **Cali metro bbox** returned **{cali.get('count', 0)}** transformers.",
        f"- **Valle del Cauca wide bbox** returned **{valle.get('count', 0)}** transformers.",
    ]
    if cali.get("count") and valle.get("count"):
        if valle["count"] > cali["count"] * 1.05:
            lines.append(
                f"- The wider Valle query returned **{valle['count'] - cali['count']}** "
                "more records than the Cali-only query → the dataset **extends beyond Cali**. "
                "Investigate which neighbors contribute."
            )
        elif valle["count"] < cali["count"] * 0.95:
            lines.append(
                "- The wider Valle query returned **fewer** records than Cali — "
                "suggests a **per-response cap** truncating the wide query."
            )
        else:
            lines.append(
                "- Valle and Cali counts are comparable → the dataset is "
                "**essentially Cali-only** (neighboring municipalities contribute negligibly), "
                "OR the wide query is hitting a cap coincidentally close to Cali's count."
            )
    lines.append("")
    lines.append("### Control regions")
    for name, s in controls:
        lines.append(f"- **{name}**: {s.get('count', 'ERROR')} records "
                     + ("(expected 0)" if s.get("count", 0) == 0
                        else "⚠️ non-zero — investigate"))

    # Neighbor breakdown.
    lines.append("")
    lines.append("### Neighboring municipalities (non-Cali)")
    for r, s in all_results:
        if r.name in ("Cali metro (documented)", "Valle del Cauca (wide)"):
            continue
        if r.name.endswith("control") or "ocean" in r.name.lower():
            continue
        lines.append(f"- **{r.name}**: {s.get('count', 0)} records")

    # Derived crawl bounds from Valle response (if it wasn't capped).
    if valle.get("count", 0) > 0 and "lat_min" in valle:
        lines += [
            "",
            "## Empirical dataset bounds (from widest successful probe)",
            "",
            f"- lat: [{valle['lat_min']:.5f}, {valle['lat_max']:.5f}]",
            f"- lng: [{valle['lng_min']:.5f}, {valle['lng_max']:.5f}]",
            "",
            "Use these as the outer envelope for the Phase B tiled crawl, "
            "padded slightly (e.g. ±0.005°).",
        ]

    OUT_MD.write_text("\n".join(lines) + "\n")
    print(f"\n[probe] wrote {OUT_MD}")
    print(f"[probe] raw per-region responses saved under {RAW_DIR}")


if __name__ == "__main__":
    main()
